name: Package Zip / Deploy âœ¨

on:
  push: { branches: [package] }

env:
  ITCH_USERNAME: mathewhd
  ITCH_GAME_ID: unity-audio-manager

jobs:
  zipPackage:
    name: Zip package repository ğŸ“
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: com.mathewhdyt.audiomanager
          recursive: true
          dest: package.zip
      - uses: actions/upload-artifact@v1
        with:
          name: package
          path: ${{ github.workspace }}/package.zip

  deployPackage:
    needs: zipPackage
    name: Deploy package to Itch.io ğŸš€
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the latest tag ğŸ·ï¸
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Download zip
        uses: actions/download-artifact@v2.0.8
        with:
          name: package
          path: ${{ github.workspace }}/package.zip

      - name: Deploy package
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ${{ github.workspace }}/
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: win-linux-mac-stable
          buildNumber: ${{ steps.get-latest-tag.outputs.tag }}
